language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
  #- pip3 install coveralls
services:
  - mysql
  - redis-server
before_script:
  - mysql < mysql_setup.sql
  - flask db upgrade
script:
  - coverage run -m pytest tests
