language: python
python:
  - "3.8"

install:
  - pip3 install -r requirements.txt

services:
  - mysql

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS testdb;'
  - flask db upgrade

script:
  - coverage run -m pytest tests

