dist: focal
language: python
python:
  - "3.10.12"  # specify the Python version you want to use

services:
  - mysql  # for MySQL database

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS weconnect_test_db;'
  - mysql -e "GRANT ALL ON weconnect_test_db.* TO 'weconnect_test'@'localhost' IDENTIFIED BY 'weconnect_pwd';"

install:
  - pip install -r requirements.txt
  #- pip install coveralls  # if you want to use coveralls for code coverage

before_script:
  - python setup_mysql_test.py  # script to setup MySQL test database

script:
  - coverage run -m pytest tests

#after_success:
  #- coveralls  # report coverage to coveralls.io

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: always
