"""update review

Revision ID: 3c8a6beebe34
Revises: 1900c5f154eb
Create Date: 2024-03-27 13:43:29.483747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c8a6beebe34'
down_revision = '1900c5f154eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review', sa.String(length=255), nullable=True))
        batch_op.drop_column('body')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('review')

    # ### end Alembic commands ###
